CREATE TABLE IF NOT EXISTS example_one (
    id bigint generated BY DEFAULT AS IDENTITY,
    field_example_one VARCHAR(255),
    field_example_two VARCHAR(255),
    PRIMARY KEY (id)
);

INSERT INTO example_one
    (id, field_example_one, field_example_two)
VALUES
    (1, 'OneOne', 'OneTwo'), (2, 'TwoOne', 'TwoTwo');


